// import './01.instance';
// import './lifecycle';
// import './data-binding';
// import './computed';
// import './05.directive';
// import './06.component/define';
// import './06.component/extend';
import './06.component/v-model';
// import './06.component/features';
// import './06.component/render';
